name: Build MyGrpcWrapper XCFramework

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Xcode 15.0.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'

      - name: Set Xcode path
        run: sudo xcode-select -s /Applications/Xcode_15.0.1.app

      - name: Clean build folders
        run: |
          rm -rf .build
          rm -f Package.resolved

      - name: Resolve dependencies
        run: swift package resolve

      - name: Archive iOS framework
        run: |
          xcodebuild archive \
            -scheme MyGrpcWrapper \
            -destination "generic/platform=iOS" \
            -archivePath build/MyGrpcWrapper-iOS.xcarchive \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=YES

      - name: Create XCFramework
        run: |
          xcodebuild -create-xcframework \
            -framework build/MyGrpcWrapper-iOS.xcarchive/Products/Library/Frameworks/MyGrpcWrapper.framework \
            -output MyGrpcWrapper.xcframework

      - name: Upload XCFramework Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyGrpcWrapper.xcframework
          path: MyGrpcWrapper.xcframework

