name: Build XCFramework

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app

    - name: Build XCFramework
      run: |
        bash ./build-xcframework.sh

    - name: Upload Release Artifact
      uses: softprops/action-gh-release@v1
      with:
        files: MyGrpcWrapper.xcframework.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

